// app/report/[id]/page.tsx
import { createAdminSupabase } from '@/lib/supabase-server';

export default async function SharedReport({ params }: { params: { id: string } }) {
  const supabase = createAdminSupabase();

  const { data: report } = await supabase
    .from('saved_routes')
    .select('*')
    .eq('id', params.id)
    .single();

  if (!report) {
    return (
      <div className="min-h-screen bg-zinc-950 text-white flex items-center justify-center">
        <h1 className="text-3xl">Report Not Found</h1>
      </div>
    );
  }

  const result = report.analysis_result || { segments: [], overall: {} };

  return (
    <div className="min-h-screen bg-zinc-950 text-white p-8">
      <div className="max-w-4xl mx-auto">
        <div className="flex items-center gap-4 mb-10">
          <div className="text-5xl">⚓</div>
          <div>
            <h1 className="text-4xl font-bold">Saltgrass Go/No-Go Report</h1>
            <p className="text-emerald-500 text-xl">{report.name}</p>
          </div>
        </div>

        <div className="bg-emerald-900/50 p-8 rounded-3xl text-center mb-10">
          <h2 className="text-4xl font-bold">{result.overall?.recommendation || 'Good to Go'}</h2>
        </div>

        <div className="space-y-8">
          {result.segments?.map((seg: any, i: number) => (
            <div key={i} className="bg-zinc-900 p-8 rounded-3xl">
              <h3 className="text-2xl font-bold mb-6">{seg.segment}</h3>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-8 text-lg">
                <div>Wind: <strong>{seg.windSpeed} kts</strong></div>
                <div>Waves: <strong>{seg.waveHeight} ft</strong></div>
                <div>Period: <strong>{seg.wavePeriod} s</strong></div>
                <div className={`font-bold ${seg.color === 'red' ? 'text-red-400' : 'text-emerald-400'}`}>
                  {seg.verdict}
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="text-center text-sm text-zinc-500 mt-16">
          Generated by <span className="text-emerald-500 font-semibold">Saltgrass</span> • Florida Outdoors App
        </div>
      </div>
    </div>
  );
}