'use client'
// src/app/crewup/page.tsx

import { useState } from 'react'
import { REGIONS } from '@/lib/types'

const B = {
  midnight:'#0A0C08', forest:'#141F14', moss:'#1C2E1C',
  canopy:'#243824', copper:'#C8922A', bone:'#E8DFC8',
  parchment:'#B8AE98', dust:'#6B6358', bark:'#1A1208',
  danger:'#C8452A', go:'#3D7A3D', goText:'#7AE07A',
}

const PLATFORM_FEE = 0.10

const TRIPS = [
  {
    id: 1, captain: 'RiverRoller88', captain_rating: 4.9, captain_trips: 34,
    avatar: '🧔', verified_phone: true, verified_photo: true,
    type: 'fishing', title: 'Inshore Redfish — Pensacola Bay',
    description: 'Half-day inshore Saturday at 5am. Targeting redfish and speckled trout on the Pensacola Bay flats. 22ft Pathfinder, 150 Yamaha. Light tackle provided if needed. Back by noon. Looking for laid-back guys who know how to handle a boat.',
    region: 'panhandle', region_icon: '🏖️', region_label: 'Panhandle',
    departure: 'Bayou Chico Boat Ramp, Pensacola, FL',
    destination: 'Pensacola Bay Flats — North Shore',
    date: 'Sat Jun 7, 2026', time: '5:00 AM', return_time: '12:00 PM',
    seats_total: 3, seats_filled: 1, cost_per_person: 45,
    cost_covers: 'Fuel + ramp fee', vessel: '2021 Pathfinder 22 HPS',
    vessel_hin: 'PFD22XYZ2021', tags: ['Redfish', 'Speckled Trout', 'Inshore'],
    requestors: [
      { id: 101, name: 'FlatsDrifter', rating: 4.8, trips: 12, photo: '🎣', verified: true, bio: 'Panhandle angler, 10 years on these waters. Know my way around a boat.', status: 'pending' },
      { id: 102, name: 'PensacolaPete', rating: 5.0, trips: 6, photo: '🧢', verified: true, bio: 'Born and raised in Pensacola. Redfish is my thing.', status: 'pending' },
    ]
  },
  {
    id: 2, captain: 'SwampBuckHunter', captain_rating: 5.0, captain_trips: 12,
    avatar: '🧢', verified_phone: true, verified_photo: true,
    type: 'hunting', title: 'Hog Hunt — Private Ranch, Ocala',
    description: 'Friday night into Saturday morning on a 400-acre private ranch outside Ocala. Spot and stalk plus feeder stands. ATV access to all areas. .308 available if needed.',
    region: 'centralfl', region_icon: '🐊', region_label: 'Central Florida',
    departure: 'Loves Truck Stop, I-75 Exit 358, Ocala FL',
    destination: 'Private Ranch — Ocala Area (address shared after confirmation)',
    date: 'Fri Jun 6, 2026', time: '7:00 PM', return_time: 'Sat Jun 7, 10:00 AM',
    seats_total: 2, seats_filled: 0, cost_per_person: 60,
    cost_covers: 'Gas + land access fee', vessel: 'F-250 + ATV trailer',
    vessel_hin: 'N/A', tags: ['Hog Hunting', 'Night Hunt', 'Private Land'],
    requestors: []
  },
]

// ── Float Plan Modal ─────────────────────────────────────────
function FloatPlan({ trip, crewNames, onClose }: { trip: typeof TRIPS[0]; crewNames: string[]; onClose: () => void }) {
  const [contact, setContact] = useState('')
  const [phone,   setPhone]   = useState('')
  const [copied,  setCopied]  = useState(false)
  const [emailed, setEmailed] = useState(false)

  const allCrew = [trip.captain, ...crewNames]
  const soulCount = allCrew.length

  const plan = `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SALTGRASS FLOAT PLAN
Generated: ${new Date().toLocaleString('en-US')}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

TRIP DESCRIPTION
${trip.title}

CAPTAIN: @${trip.captain}
CREW: ${crewNames.length > 0 ? crewNames.map(n => '@'+n).join(', ') : 'TBD'}
TOTAL SOULS ABOARD: ${soulCount}

VESSEL
Name/Type: ${trip.vessel}
HIN: ${trip.vessel_hin}

DEPARTURE
Location: ${trip.departure}
Date & Time: ${trip.date} at ${trip.time}

DESTINATION
${trip.destination}

EXPECTED RETURN
${trip.return_time} on ${trip.date.includes('Sat') ? trip.date : trip.date}

EMERGENCY CONTACT ON SHORE
Name: ${contact || '[FILL IN BEFORE DEPARTURE]'}
Phone: ${phone || '[FILL IN BEFORE DEPARTURE]'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EMERGENCY CONTACTS

US Coast Guard Distress: VHF Channel 16
Coast Guard Emergency Hotline: 1-800-424-8802
Florida Marine Patrol: *FMP (*367) from cell
Local Sheriff: 911

IF VESSEL HAS NOT RETURNED BY ${trip.return_time}:
Contact the US Coast Guard immediately at
VHF Channel 16 or 1-800-424-8802 and
provide this float plan.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Generated by Saltgrass · saltgrass-3scu.vercel.app
Trip verified by Saltgrass identity system`

  return (
    <div style={{ position:'fixed', inset:0, background:'rgba(0,0,0,0.9)', zIndex:600, display:'flex', alignItems:'center', justifyContent:'center', padding:16, overflowY:'auto' }}>
      <div style={{ background:B.forest, borderRadius:8, padding:28, maxWidth:520, width:'100%', border:`1px solid ${B.canopy}`, maxHeight:'90vh', overflowY:'auto' }}>

        <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:20 }}>
          <div>
            <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:10, letterSpacing:3, color:B.copper, marginBottom:3 }}>CREW UP</div>
            <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:20, letterSpacing:2, color:B.bone }}>FLOAT PLAN</div>
          </div>
          <button onClick={onClose} style={{ background:B.moss, border:'none', borderRadius:4, color:B.dust, padding:'6px 12px', cursor:'pointer', fontSize:13 }}>✕ CLOSE</button>
        </div>

        <div style={{ background:'rgba(200,146,42,0.08)', border:`1px solid ${B.copper}44`, borderRadius:6, padding:'12px 14px', marginBottom:18, fontSize:12, color:B.parchment, lineHeight:1.7 }}>
          <strong style={{ color:B.copper }}>File this with someone on shore before you launch.</strong> The Coast Guard recommends it every time. Takes 60 seconds and could save your life.
        </div>

        {/* Emergency contact */}
        <div style={{ marginBottom:16 }}>
          <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:10, letterSpacing:3, color:B.danger, marginBottom:10 }}>🚨 EMERGENCY CONTACT ON SHORE</div>
          <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:10 }}>
            <div>
              <label style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:9, letterSpacing:2, color:B.dust, display:'block', marginBottom:5 }}>CONTACT NAME</label>
              <input value={contact} onChange={e => setContact(e.target.value)} placeholder="Wife, buddy, family..." style={{ background:B.bark, border:`1.5px solid ${B.canopy}`, borderRadius:4, color:B.bone, fontSize:13, padding:'9px 12px', width:'100%', outline:'none', boxSizing:'border-box' as any }} />
            </div>
            <div>
              <label style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:9, letterSpacing:2, color:B.dust, display:'block', marginBottom:5 }}>THEIR PHONE</label>
              <input value={phone} onChange={e => setPhone(e.target.value)} placeholder="(850) 555-0100" style={{ background:B.bark, border:`1.5px solid ${B.canopy}`, borderRadius:4, color:B.bone, fontSize:13, padding:'9px 12px', width:'100%', outline:'none', boxSizing:'border-box' as any }} />
            </div>
          </div>
        </div>

        {/* Plan preview */}
        <div style={{ background:B.bark, borderRadius:4, padding:16, marginBottom:16, fontFamily:'monospace', fontSize:11, color:B.parchment, lineHeight:1.8, whiteSpace:'pre-line', border:`1px solid ${B.canopy}`, maxHeight:280, overflowY:'auto' }}>
          {plan}
        </div>

        {/* Coast Guard */}
        <div style={{ background:'rgba(200,69,42,0.08)', border:`1px solid ${B.danger}44`, borderRadius:6, padding:'10px 14px', marginBottom:16 }}>
          <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:9, letterSpacing:2, color:B.danger, marginBottom:4 }}>US COAST GUARD</div>
          <div style={{ fontSize:11, color:B.parchment, lineHeight:1.6 }}>
            VHF Channel 16 · Emergency: <strong style={{ color:B.bone }}>1-800-424-8802</strong><br/>
            Florida Marine Patrol: <strong style={{ color:B.bone }}>*FMP from any cell phone</strong>
          </div>
        </div>

        {/* Actions */}
        <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr 1fr', gap:8 }}>
          <button onClick={() => { navigator.clipboard.writeText(plan); setCopied(true); setTimeout(() => setCopied(false), 2500) }} style={{ background:B.moss, color:B.bone, border:`1px solid ${B.canopy}`, borderRadius:4, padding:'11px', fontFamily:'Impact,Arial Black,sans-serif', fontSize:10, letterSpacing:1, cursor:'pointer' }}>
            {copied ? '✓ COPIED' : '📋 COPY'}
          </button>
          <button onClick={() => { window.open(`mailto:${contact ? '' : ''}?subject=${encodeURIComponent('Float Plan — '+trip.title)}&body=${encodeURIComponent(plan)}`); setEmailed(true) }} style={{ background:B.moss, color:B.bone, border:`1px solid ${B.canopy}`, borderRadius:4, padding:'11px', fontFamily:'Impact,Arial Black,sans-serif', fontSize:10, letterSpacing:1, cursor:'pointer' }}>
            {emailed ? '✓ OPENED' : '📧 EMAIL'}
          </button>
          <button onClick={() => window.print()} style={{ background:B.moss, color:B.bone, border:`1px solid ${B.canopy}`, borderRadius:4, padding:'11px', fontFamily:'Impact,Arial Black,sans-serif', fontSize:10, letterSpacing:1, cursor:'pointer' }}>
            🖨️ PRINT
          </button>
        </div>

        <div style={{ marginTop:12, fontSize:10, color:B.dust, textAlign:'center', lineHeight:1.6 }}>
          Share this link before departure: <span style={{ color:B.copper }}>saltgrass.app/float/{trip.id}</span>
        </div>
      </div>
    </div>
  )
}

// ── Seat Request Modal ───────────────────────────────────────
function RequestModal({ trip, onClose }: { trip: typeof TRIPS[0]; onClose: () => void }) {
  const [step, setStep] = useState(1)
  const [verifyStep, setVerifyStep] = useState(1)
  const [phone, setPhone] = useState('')
  const [code, setCode] = useState('')
  const [note, setNote] = useState('')
  const fee = Math.round(trip.cost_per_person * PLATFORM_FEE)
  const total = trip.cost_per_person + fee

  return (
    <div style={{ position:'fixed', inset:0, background:'rgba(0,0,0,0.9)', zIndex:600, display:'flex', alignItems:'center', justifyContent:'center', padding:16 }}>
      <div style={{ background:B.forest, borderRadius:8, padding:28, maxWidth:460, width:'100%', border:`1px solid ${B.canopy}` }}>

        {/* Steps indicator */}
        <div style={{ display:'flex', gap:6, marginBottom:20 }}>
          {['VERIFY', 'REVIEW', 'CONFIRM'].map((s,i) => (
            <div key={s} style={{ flex:1 }}>
              <div style={{ height:3, borderRadius:2, background: i+1 <= step ? B.copper : B.canopy, marginBottom:4 }} />
              <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:8, letterSpacing:1, color: i+1 <= step ? B.copper : B.dust, textAlign:'center' }}>{s}</div>
            </div>
          ))}
        </div>

        {/* STEP 1 — Identity Verification */}
        {step === 1 && (
          <div>
            <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:16, letterSpacing:2, color:B.bone, marginBottom:6 }}>VERIFY YOUR IDENTITY</div>
            <p style={{ fontSize:12, color:B.parchment, lineHeight:1.7, marginBottom:20 }}>
              Crew Up requires identity verification before you can request a seat. The captain needs to know who's getting on their boat. This is a one-time step.
            </p>

            {verifyStep === 1 && (
              <div>
                <div style={{ background:B.moss, borderRadius:6, padding:'14px 16px', marginBottom:16, border:`1px solid ${B.canopy}` }}>
                  <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:10, letterSpacing:2, color:B.copper, marginBottom:10 }}>WHAT WE VERIFY</div>
                  {[
                    { icon:'📱', label:'Phone number', desc:'SMS confirmation to a real US number' },
                    { icon:'📷', label:'Profile photo', desc:'A clear photo of your face — no avatars' },
                    { icon:'✅', label:'Real name', desc:'Must match your Saltgrass profile' },
                  ].map(v => (
                    <div key={v.label} style={{ display:'flex', gap:10, padding:'6px 0', borderBottom:`1px solid ${B.canopy}` }}>
                      <span style={{ fontSize:18, flexShrink:0 }}>{v.icon}</span>
                      <div>
                        <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:10, letterSpacing:1, color:B.bone }}>{v.label}</div>
                        <div style={{ fontSize:11, color:B.dust }}>{v.desc}</div>
                      </div>
                    </div>
                  ))}
                </div>
                <button onClick={() => setVerifyStep(2)} style={{ width:'100%', background:B.copper, color:'#0A0C08', border:'none', borderRadius:4, padding:'13px', fontFamily:'Impact,Arial Black,sans-serif', fontSize:13, letterSpacing:2, cursor:'pointer' }}>
                  START VERIFICATION →
                </button>
              </div>
            )}

            {verifyStep === 2 && (
              <div>
                <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:12, letterSpacing:2, color:B.bone, marginBottom:12 }}>📱 VERIFY PHONE NUMBER</div>
                <label style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:9, letterSpacing:2, color:B.dust, display:'block', marginBottom:6 }}>YOUR PHONE NUMBER</label>
                <input value={phone} onChange={e => setPhone(e.target.value)} placeholder="(850) 555-0100" type="tel"
                  style={{ background:B.bark, border:`1.5px solid ${B.canopy}`, borderRadius:4, color:B.bone, fontSize:15, padding:'11px 14px', width:'100%', outline:'none', boxSizing:'border-box' as any, marginBottom:12 }} />
                <button onClick={() => setVerifyStep(3)} style={{ width:'100%', background:B.copper, color:'#0A0C08', border:'none', borderRadius:4, padding:'13px', fontFamily:'Impact,Arial Black,sans-serif', fontSize:13, letterSpacing:2, cursor:'pointer' }}>
                  SEND CODE
                </button>
              </div>
            )}

            {verifyStep === 3 && (
              <div>
                <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:12, letterSpacing:2, color:B.bone, marginBottom:6 }}>ENTER 6-DIGIT CODE</div>
                <div style={{ fontSize:12, color:B.dust, marginBottom:14 }}>Sent to {phone || 'your phone'}</div>
                <input value={code} onChange={e => setCode(e.target.value)} placeholder="000000" maxLength={6}
                  style={{ background:B.bark, border:`1.5px solid ${B.canopy}`, borderRadius:4, color:B.copper, fontSize:24, fontWeight:700, padding:'14px', width:'100%', outline:'none', boxSizing:'border-box' as any, textAlign:'center', letterSpacing:8, marginBottom:14 }} />
                <button onClick={() => { if(code.length === 6) setStep(2) }} style={{ width:'100%', background: code.length===6 ? B.copper : B.canopy, color: code.length===6 ? '#0A0C08' : B.dust, border:'none', borderRadius:4, padding:'13px', fontFamily:'Impact,Arial Black,sans-serif', fontSize:13, letterSpacing:2, cursor: code.length===6 ? 'pointer' : 'not-allowed' }}>
                  VERIFY →
                </button>
                <button onClick={() => setVerifyStep(2)} style={{ width:'100%', background:'none', border:'none', color:B.dust, fontSize:12, marginTop:8, cursor:'pointer' }}>
                  ← Change number
                </button>
              </div>
            )}
          </div>
        )}

        {/* STEP 2 — Review trip + add note */}
        {step === 2 && (
          <div>
            <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:16, letterSpacing:2, color:B.bone, marginBottom:16 }}>REVIEW & REQUEST</div>

            {/* Trip summary */}
            <div style={{ background:B.moss, borderRadius:6, padding:14, marginBottom:16, border:`1px solid ${B.canopy}` }}>
              <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:13, color:B.bone, marginBottom:6 }}>{trip.title}</div>
              <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:'5px 16px', fontSize:11, color:B.parchment }}>
                <div>📅 {trip.date}</div>
                <div>⏰ {trip.time}</div>
                <div>📍 {trip.departure.split(',')[0]}</div>
                <div>⛵ {trip.vessel.split(' ').slice(0,3).join(' ')}</div>
              </div>
            </div>

            {/* Cost */}
            <div style={{ background:B.bark, borderRadius:4, padding:'12px 14px', marginBottom:16, border:`1px solid ${B.canopy}` }}>
              <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:9, letterSpacing:2, color:B.dust, marginBottom:8 }}>COST BREAKDOWN</div>
              {[
                { label:'Trip cost ('+trip.cost_covers+')', val:`$${trip.cost_per_person}` },
                { label:`Saltgrass platform fee (${PLATFORM_FEE*100}%)`, val:`$${fee}` },
              ].map((r,i) => (
                <div key={i} style={{ display:'flex', justifyContent:'space-between', padding:'4px 0', borderBottom:`1px solid ${B.canopy}` }}>
                  <span style={{ fontSize:12, color:B.parchment }}>{r.label}</span>
                  <span style={{ fontSize:12, color:B.bone, fontWeight:700 }}>{r.val}</span>
                </div>
              ))}
              <div style={{ display:'flex', justifyContent:'space-between', paddingTop:8 }}>
                <span style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:12, letterSpacing:1, color:B.bone }}>TOTAL</span>
                <span style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:20, color:B.copper }}>${total}</span>
              </div>
            </div>

            {/* Note to captain */}
            <div style={{ marginBottom:16 }}>
              <label style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:9, letterSpacing:2, color:B.dust, display:'block', marginBottom:6 }}>NOTE TO CAPTAIN (OPTIONAL)</label>
              <textarea value={note} onChange={e => setNote(e.target.value)} rows={3}
                placeholder="Introduce yourself. Your experience level, what you fish/hunt, why you want to join..."
                style={{ background:B.bark, border:`1.5px solid ${B.canopy}`, borderRadius:4, color:B.bone, fontSize:13, padding:'10px 12px', width:'100%', outline:'none', resize:'none' as any, boxSizing:'border-box' as any, fontFamily:'Inter,sans-serif', lineHeight:1.6 }} />
            </div>

            <div style={{ background:'rgba(200,146,42,0.08)', border:`1px solid ${B.copper}44`, borderRadius:6, padding:'10px 14px', marginBottom:16, fontSize:11, color:B.parchment, lineHeight:1.6 }}>
              📋 Payment held until trip completes. Float plan sent to both parties when captain confirms.
            </div>

            <div style={{ display:'flex', gap:8 }}>
              <button onClick={() => setStep(1)} style={{ flex:1, padding:'12px', background:'transparent', border:`1.5px solid ${B.canopy}`, borderRadius:4, color:B.parchment, fontFamily:'Impact,Arial Black,sans-serif', fontSize:11, letterSpacing:1, cursor:'pointer' }}>← BACK</button>
              <button onClick={() => setStep(3)} style={{ flex:2, background:B.copper, color:'#0A0C08', border:'none', borderRadius:4, padding:'12px', fontFamily:'Impact,Arial Black,sans-serif', fontSize:12, letterSpacing:1, cursor:'pointer' }}>
                SEND REQUEST →
              </button>
            </div>
          </div>
        )}

        {/* STEP 3 — Confirmed */}
        {step === 3 && (
          <div style={{ textAlign:'center', padding:'10px 0' }}>
            <div style={{ fontSize:52, marginBottom:14 }}>⛵</div>
            <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:18, letterSpacing:2, color:B.bone, marginBottom:8 }}>REQUEST SENT!</div>
            <div style={{ fontSize:13, color:B.parchment, lineHeight:1.8, marginBottom:16 }}>
              @{trip.captain} will review your profile and respond within 24 hours. You'll get a notification either way.
            </div>

            {/* What happens next */}
            <div style={{ background:B.moss, borderRadius:6, padding:14, marginBottom:16, textAlign:'left', border:`1px solid ${B.canopy}` }}>
              <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:9, letterSpacing:2, color:B.copper, marginBottom:10 }}>WHAT HAPPENS NEXT</div>
              {[
                { icon:'1️⃣', text:`@${trip.captain} reviews your profile and either accepts or declines` },
                { icon:'2️⃣', text:'If accepted — payment of $'+total+' is charged and held in escrow' },
                { icon:'3️⃣', text:'Float plan auto-generated and emailed to both parties' },
                { icon:'4️⃣', text:'After the trip — both sides rate each other' },
              ].map(s => (
                <div key={s.icon} style={{ display:'flex', gap:10, padding:'5px 0', fontSize:12, color:B.parchment }}>
                  <span>{s.icon}</span><span>{s.text}</span>
                </div>
              ))}
            </div>

            <button onClick={onClose} style={{ background:B.copper, color:'#0A0C08', border:'none', borderRadius:4, padding:'12px 28px', fontFamily:'Impact,Arial Black,sans-serif', fontSize:13, letterSpacing:2, cursor:'pointer' }}>
              DONE
            </button>
          </div>
        )}

        {step < 3 && (
          <button onClick={onClose} style={{ width:'100%', marginTop:12, background:'none', border:'none', color:B.dust, fontSize:12, cursor:'pointer' }}>Cancel</button>
        )}
      </div>
    </div>
  )
}

// ── Captain Accept/Decline Modal ─────────────────────────────
function CaptainReviewModal({ trip, onClose }: { trip: typeof TRIPS[0]; onClose: () => void }) {
  const [decisions, setDecisions] = useState<Record<number,string>>({})
  const [floatFor, setFloatFor] = useState<string[]>([])

  function decide(id: number, val: string) {
    setDecisions(d => ({ ...d, [id]: val }))
    if (val === 'accept') setFloatFor(f => [...f, trip.requestors.find(r=>r.id===id)?.name ?? ''])
  }

  return (
    <div style={{ position:'fixed', inset:0, background:'rgba(0,0,0,0.9)', zIndex:600, display:'flex', alignItems:'center', justifyContent:'center', padding:16 }}>
      <div style={{ background:B.forest, borderRadius:8, padding:28, maxWidth:500, width:'100%', border:`1px solid ${B.canopy}`, maxHeight:'90vh', overflowY:'auto' }}>

        <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:20 }}>
          <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:16, letterSpacing:2, color:B.bone }}>REVIEW REQUESTS</div>
          <button onClick={onClose} style={{ background:B.moss, border:'none', borderRadius:4, color:B.dust, padding:'6px 12px', cursor:'pointer' }}>✕</button>
        </div>

        <div style={{ background:B.moss, borderRadius:6, padding:'10px 14px', marginBottom:16, fontSize:12, color:B.parchment, lineHeight:1.6 }}>
          You control who gets on your boat. Review each request, check their profile and ratings, then accept or decline. Declined members are notified politely.
        </div>

        {trip.requestors.length === 0 ? (
          <div style={{ textAlign:'center', padding:'30px 0', color:B.dust, fontSize:13 }}>No requests yet for this trip.</div>
        ) : (
          trip.requestors.map(r => (
            <div key={r.id} style={{ background:B.moss, borderRadius:6, padding:16, marginBottom:12, border:`1px solid ${decisions[r.id] === 'accept' ? B.go : decisions[r.id] === 'decline' ? B.danger : B.canopy}` }}>
              <div style={{ display:'flex', gap:12, marginBottom:10 }}>
                <div style={{ width:46, height:46, borderRadius:'50%', background:B.canopy, display:'flex', alignItems:'center', justifyContent:'center', fontSize:22, flexShrink:0 }}>{r.photo}</div>
                <div style={{ flex:1 }}>
                  <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:14, color:B.bone }}>@{r.name}</div>
                  <div style={{ display:'flex', gap:8, alignItems:'center', marginTop:2 }}>
                    <span style={{ color:B.copper, fontSize:12 }}>{'★'.repeat(Math.floor(r.rating))}</span>
                    <span style={{ fontSize:11, color:B.dust }}>{r.rating} · {r.trips} trips</span>
                    {r.verified && <span style={{ background:'rgba(200,146,42,0.2)', color:B.copper, borderRadius:4, padding:'1px 6px', fontSize:9, fontFamily:'Impact,Arial Black,sans-serif', letterSpacing:1 }}>✓ VERIFIED</span>}
                  </div>
                </div>
              </div>

              <div style={{ fontSize:12, color:B.parchment, lineHeight:1.6, marginBottom:12 }}>{r.bio}</div>

              {!decisions[r.id] ? (
                <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:8 }}>
                  <button onClick={() => decide(r.id, 'accept')} style={{ background:B.go, color:B.goText, border:'none', borderRadius:4, padding:'10px', fontFamily:'Impact,Arial Black,sans-serif', fontSize:11, letterSpacing:1, cursor:'pointer' }}>
                    ✓ ACCEPT
                  </button>
                  <button onClick={() => decide(r.id, 'decline')} style={{ background:'rgba(200,69,42,0.2)', color:'#E07A7A', border:`1px solid ${B.danger}44`, borderRadius:4, padding:'10px', fontFamily:'Impact,Arial Black,sans-serif', fontSize:11, letterSpacing:1, cursor:'pointer' }}>
                    ✕ DECLINE
                  </button>
                </div>
              ) : (
                <div style={{ textAlign:'center', padding:'8px', borderRadius:4, background: decisions[r.id]==='accept' ? 'rgba(61,122,61,0.2)' : 'rgba(200,69,42,0.15)', border:`1px solid ${decisions[r.id]==='accept' ? B.go : B.danger}44` }}>
                  <span style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:12, letterSpacing:1, color: decisions[r.id]==='accept' ? B.goText : '#E07A7A' }}>
                    {decisions[r.id]==='accept' ? '✓ ACCEPTED — Float plan will be sent' : '✕ DECLINED — Member will be notified'}
                  </span>
                </div>
              )}
            </div>
          ))
        )}

        {floatFor.length > 0 && (
          <div style={{ background:'rgba(200,146,42,0.08)', border:`1px solid ${B.copper}44`, borderRadius:6, padding:'12px 14px', marginTop:8, fontSize:12, color:B.parchment, lineHeight:1.6 }}>
            📋 Float plan will be auto-generated and emailed to you and {floatFor.map(n=>'@'+n).join(', ')} when you close this.
          </div>
        )}

        <button onClick={onClose} style={{ width:'100%', marginTop:16, background:B.copper, color:'#0A0C08', border:'none', borderRadius:4, padding:'13px', fontFamily:'Impact,Arial Black,sans-serif', fontSize:13, letterSpacing:2, cursor:'pointer' }}>
          SAVE DECISIONS
        </button>
      </div>
    </div>
  )
}

// ── Trip Card ────────────────────────────────────────────────
function TripCard({ trip, onRequest, onFloat, onReview, isOwn }: { trip: typeof TRIPS[0]; onRequest: ()=>void; onFloat: ()=>void; onReview: ()=>void; isOwn?: boolean }) {
  const seatsLeft = trip.seats_total - trip.seats_filled
  const fee = Math.round(trip.cost_per_person * PLATFORM_FEE)
  const total = trip.cost_per_person + fee

  return (
    <div style={{ background:B.forest, border:`1px solid ${B.canopy}`, borderRadius:8, overflow:'hidden', marginBottom:10 }}>
      <div style={{ background: trip.type==='fishing' ? '#0F1A2A' : '#1A2B1A', padding:'8px 16px', display:'flex', justifyContent:'space-between', alignItems:'center' }}>
        <span style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:10, letterSpacing:3, color: trip.type==='fishing' ? '#5A9FD4' : B.copper }}>
          {trip.type==='fishing' ? '🎣 FISHING' : '🏹 HUNTING'}
        </span>
        <div style={{ display:'flex', gap:8, alignItems:'center' }}>
          <span style={{ fontSize:10, color:B.dust }}>{trip.region_icon} {trip.region_label}</span>
          {trip.verified_phone && trip.verified_photo && <span style={{ background:'rgba(200,146,42,0.2)', color:B.copper, borderRadius:4, padding:'1px 7px', fontSize:9, fontFamily:'Impact,Arial Black,sans-serif', letterSpacing:1 }}>✓ VERIFIED</span>}
        </div>
      </div>

      <div style={{ padding:'16px 18px' }}>
        <div style={{ display:'flex', gap:12, marginBottom:12, alignItems:'flex-start' }}>
          <div style={{ width:44, height:44, borderRadius:'50%', background:B.canopy, display:'flex', alignItems:'center', justifyContent:'center', fontSize:20, border:`2px solid ${B.canopy}`, flexShrink:0 }}>{trip.avatar}</div>
          <div style={{ flex:1 }}>
            <div style={{ fontWeight:700, fontSize:13, color:B.bone }}>@{trip.captain}</div>
            <div style={{ display:'flex', gap:8, alignItems:'center' }}>
              <span style={{ color:B.copper, fontSize:11 }}>{'★'.repeat(Math.floor(trip.captain_rating))}</span>
              <span style={{ fontSize:10, color:B.dust }}>{trip.captain_rating} · {trip.captain_trips} trips</span>
              <span style={{ fontSize:10, color:B.dust }}>· 📱 Phone verified</span>
            </div>
          </div>
          <div style={{ textAlign:'right', flexShrink:0 }}>
            <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:20, color:B.copper }}>${total}</div>
            <div style={{ fontSize:9, color:B.dust }}>per person total</div>
            <div style={{ fontSize:9, color:B.dust }}>(incl. ${fee} fee)</div>
          </div>
        </div>

        <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:15, letterSpacing:1, color:B.bone, marginBottom:6 }}>{trip.title}</div>
        <div style={{ fontSize:12, color:B.parchment, lineHeight:1.7, marginBottom:12, overflow:'hidden', display:'-webkit-box', WebkitLineClamp:2, WebkitBoxOrient:'vertical' as any }}>{trip.description}</div>

        <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:7, marginBottom:12 }}>
          {[['📅','DATE',trip.date],['⏰','DEPARTS',trip.time],['📍','MEET AT',trip.departure.split(',')[0]],['⛵','VESSEL',trip.vessel.split(' ').slice(0,3).join(' ')]].map(([icon,label,val]) => (
            <div key={String(label)} style={{ background:B.moss, borderRadius:4, padding:'8px 10px' }}>
              <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:8, letterSpacing:2, color:B.dust, marginBottom:2 }}>{icon} {label}</div>
              <div style={{ fontSize:11, color:B.bone, fontWeight:600 }}>{val}</div>
            </div>
          ))}
        </div>

        {/* Seats bar */}
        <div style={{ marginBottom:12 }}>
          <div style={{ display:'flex', justifyContent:'space-between', marginBottom:4 }}>
            <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:9, letterSpacing:2, color:B.dust }}>SEATS</div>
            <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:11, color: seatsLeft===0 ? B.danger : B.copper }}>{seatsLeft===0 ? 'FULL' : `${seatsLeft} LEFT`}</div>
          </div>
          <div style={{ height:5, background:B.canopy, borderRadius:3, overflow:'hidden' }}>
            <div style={{ height:'100%', width:`${(trip.seats_filled/trip.seats_total)*100}%`, background: seatsLeft===0 ? B.danger : B.copper, borderRadius:3 }} />
          </div>
          <div style={{ display:'flex', gap:6, marginTop:6 }}>
            {Array.from({length:trip.seats_total}).map((_,i) => (
              <div key={i} style={{ width:26, height:26, borderRadius:'50%', background: i<trip.seats_filled ? B.copper : B.canopy, display:'flex', alignItems:'center', justifyContent:'center', fontSize:12 }}>
                {i<trip.seats_filled ? '🧑' : ''}
              </div>
            ))}
            <span style={{ fontSize:10, color:B.dust, alignSelf:'center', marginLeft:4 }}>{trip.seats_filled}/{trip.seats_total} crew confirmed</span>
          </div>
        </div>

        <div style={{ display:'flex', gap:6, flexWrap:'wrap', marginBottom:14 }}>
          {trip.tags.map(t => <span key={t} style={{ background:B.moss, color:B.parchment, borderRadius:4, padding:'2px 8px', fontSize:10 }}>#{t}</span>)}
        </div>

        <div style={{ display:'flex', gap:7 }}>
          <button onClick={onFloat} style={{ flex:1, background:'transparent', color:B.parchment, border:`1.5px solid ${B.canopy}`, borderRadius:4, padding:'9px', fontFamily:'Impact,Arial Black,sans-serif', fontSize:9, letterSpacing:1, cursor:'pointer' }}>
            📋 FLOAT PLAN
          </button>
          {isOwn ? (
            <button onClick={onReview} style={{ flex:2, background:B.copper, color:'#0A0C08', border:'none', borderRadius:4, padding:'9px', fontFamily:'Impact,Arial Black,sans-serif', fontSize:11, letterSpacing:1, cursor:'pointer', position:'relative' as any }}>
              REVIEW REQUESTS {trip.requestors.length > 0 && <span style={{ background:B.danger, color:'#fff', borderRadius:'50%', width:18, height:18, fontSize:10, fontWeight:800, display:'inline-flex', alignItems:'center', justifyContent:'center', marginLeft:6 }}>{trip.requestors.length}</span>}
            </button>
          ) : (
            <button onClick={onRequest} disabled={seatsLeft===0} style={{ flex:2, background: seatsLeft===0 ? B.canopy : B.copper, color: seatsLeft===0 ? B.dust : '#0A0C08', border:'none', borderRadius:4, padding:'9px', fontFamily:'Impact,Arial Black,sans-serif', fontSize:11, letterSpacing:1, cursor: seatsLeft===0 ? 'not-allowed' : 'pointer' }}>
              {seatsLeft===0 ? 'TRIP FULL' : `REQUEST SEAT — $${total}`}
            </button>
          )}
        </div>
      </div>
    </div>
  )
}

// ── Post Trip Modal ──────────────────────────────────────────
function PostTripModal({ onClose }: { onClose: ()=>void }) {
  const [form, setForm] = useState({ type:'fishing', title:'', description:'', region_id:'', departure:'', destination:'', date:'', time:'', return_time:'', seats:'2', cost_per_person:'', cost_covers:'', vessel:'' })
  const set = (k: string, v: string) => setForm(f => ({...f,[k]:v}))
  const captainGets = form.cost_per_person ? Number(form.cost_per_person) : 0
  const crewPays = captainGets ? Math.round(captainGets * (1 + PLATFORM_FEE)) : 0

  return (
    <div style={{ position:'fixed', inset:0, background:'rgba(0,0,0,0.9)', zIndex:600, display:'flex', alignItems:'center', justifyContent:'center', padding:16 }}>
      <div style={{ background:B.forest, borderRadius:8, padding:26, maxWidth:560, width:'100%', border:`1px solid ${B.canopy}`, maxHeight:'90vh', overflowY:'auto' }}>
        <div style={{ display:'flex', justifyContent:'space-between', marginBottom:20 }}>
          <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:18, letterSpacing:2, color:B.bone }}>POST A TRIP</div>
          <button onClick={onClose} style={{ background:B.moss, border:'none', borderRadius:4, color:B.dust, padding:'6px 12px', cursor:'pointer' }}>✕</button>
        </div>

        <div style={{ display:'flex', flexDirection:'column', gap:14 }}>
          <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:8 }}>
            {[['fishing','🎣 FISHING'],['hunting','🏹 HUNTING']].map(([id,label]) => (
              <button key={id} type="button" onClick={() => set('type',id)} style={{ padding:'11px', borderRadius:4, border:`2px solid ${form.type===id ? B.copper : B.canopy}`, background: form.type===id ? 'rgba(200,146,42,0.12)' : 'transparent', color: form.type===id ? B.copper : B.parchment, fontFamily:'Impact,Arial Black,sans-serif', fontSize:13, letterSpacing:2, cursor:'pointer' }}>
                {label}
              </button>
            ))}
          </div>

          {[
            {k:'title',      l:'TRIP TITLE',            p:'Inshore Redfish — Pensacola Bay'},
            {k:'departure',  l:'MEET / DEPARTURE POINT',p:'Bayou Chico Boat Ramp, Pensacola FL'},
            {k:'destination',l:'WHERE YOU\'RE HEADED',  p:'Pensacola Bay North Flats'},
            {k:'vessel',     l:'VESSEL OR VEHICLE',     p:'2021 Pathfinder 22 HPS'},
            {k:'cost_covers',l:'COST COVERS',           p:'Fuel + ramp fee'},
          ].map(({k,l,p}) => (
            <div key={k}>
              <label style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:9, letterSpacing:2, color:B.dust, display:'block', marginBottom:5 }}>{l}</label>
              <input value={(form as any)[k]} onChange={e => set(k,e.target.value)} placeholder={p} style={{ background:B.bark, border:`1.5px solid ${B.canopy}`, borderRadius:4, color:B.bone, fontSize:13, padding:'10px 12px', width:'100%', outline:'none', boxSizing:'border-box' as any }} />
            </div>
          ))}

          <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr 1fr', gap:10 }}>
            {[['date','DATE','date'],['time','DEPARTS','time'],['return_time','RETURNS','time']].map(([k,l,t]) => (
              <div key={k}>
                <label style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:9, letterSpacing:2, color:B.dust, display:'block', marginBottom:5 }}>{l}</label>
                <input type={t} value={(form as any)[k]} onChange={e => set(k,e.target.value)} style={{ background:B.bark, border:`1.5px solid ${B.canopy}`, borderRadius:4, color:B.bone, fontSize:12, padding:'10px 10px', width:'100%', outline:'none', boxSizing:'border-box' as any }} />
              </div>
            ))}
          </div>

          <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:10 }}>
            <div>
              <label style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:9, letterSpacing:2, color:B.dust, display:'block', marginBottom:5 }}>OPEN SEATS</label>
              <select value={form.seats} onChange={e => set('seats',e.target.value)} style={{ background:B.bark, border:`1.5px solid ${B.canopy}`, borderRadius:4, color:B.bone, fontSize:13, padding:'10px 12px', width:'100%', outline:'none', cursor:'pointer' }}>
                {['1','2','3','4','5','6'].map(n => <option key={n} value={n}>{n} seat{Number(n)!==1?'s':''}</option>)}
              </select>
            </div>
            <div>
              <label style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:9, letterSpacing:2, color:B.dust, display:'block', marginBottom:5 }}>COST PER SEAT ($)</label>
              <input type="number" value={form.cost_per_person} onChange={e => set('cost_per_person',e.target.value)} placeholder="45" style={{ background:B.bark, border:`1.5px solid ${B.canopy}`, borderRadius:4, color:B.bone, fontSize:16, fontWeight:700, padding:'10px 12px', width:'100%', outline:'none', boxSizing:'border-box' as any }} />
            </div>
          </div>

          {captainGets > 0 && (
            <div style={{ background:B.bark, borderRadius:4, padding:'12px 14px', border:`1px solid ${B.canopy}` }}>
              <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:9, letterSpacing:2, color:B.dust, marginBottom:8 }}>EARNINGS PREVIEW</div>
              {[
                {l:'Each crew member pays', v:`$${crewPays}`},
                {l:`Saltgrass fee (${PLATFORM_FEE*100}%) — paid by crew`, v:'Included above'},
                {l:'You collect per seat', v:`$${captainGets}`},
                {l:`Total payout (${form.seats} seats)`, v:`$${captainGets * Number(form.seats)}`},
              ].map((r,i) => (
                <div key={i} style={{ display:'flex', justifyContent:'space-between', padding:'4px 0', borderBottom: i<3 ? `1px solid ${B.canopy}` : 'none' }}>
                  <span style={{ fontSize:11, color:B.parchment }}>{r.l}</span>
                  <span style={{ fontSize:11, fontWeight:700, color: i===3 ? B.copper : B.bone }}>{r.v}</span>
                </div>
              ))}
            </div>
          )}

          <div>
            <label style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:9, letterSpacing:2, color:B.dust, display:'block', marginBottom:5 }}>REGION</label>
            <select value={form.region_id} onChange={e => set('region_id',e.target.value)} style={{ background:B.bark, border:`1.5px solid ${B.canopy}`, borderRadius:4, color: form.region_id ? B.bone : B.dust, fontSize:13, padding:'10px 12px', width:'100%', outline:'none', cursor:'pointer' }}>
              <option value="">Select region...</option>
              {REGIONS.map(r => <option key={r.id} value={r.id}>{r.icon} {r.label}</option>)}
            </select>
          </div>

          <div>
            <label style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:9, letterSpacing:2, color:B.dust, display:'block', marginBottom:5 }}>TRIP DETAILS</label>
            <textarea value={form.description} onChange={e => set('description',e.target.value)} rows={3} placeholder="Target species, experience level needed, what to bring, what's provided..." style={{ background:B.bark, border:`1.5px solid ${B.canopy}`, borderRadius:4, color:B.bone, fontSize:13, padding:'10px 12px', width:'100%', outline:'none', resize:'none' as any, boxSizing:'border-box' as any, fontFamily:'Inter,sans-serif', lineHeight:1.6 }} />
          </div>

          <div style={{ background:'rgba(200,146,42,0.08)', border:`1px solid ${B.copper}44`, borderRadius:6, padding:'10px 14px', fontSize:11, color:B.parchment, lineHeight:1.6 }}>
            📋 <strong style={{ color:B.copper }}>Float plan auto-generated</strong> when you confirm a crew member. Share it with someone on shore before departure.
          </div>

          <button onClick={onClose} style={{ width:'100%', background:B.copper, color:'#0A0C08', border:'none', borderRadius:4, padding:'13px', fontFamily:'Impact,Arial Black,sans-serif', fontSize:14, letterSpacing:2, cursor:'pointer' }}>
            POST TRIP
          </button>
        </div>
      </div>
    </div>
  )
}

// ── Main Page ────────────────────────────────────────────────
export default function CrewUpPage() {
  const [typeFilter, setTypeFilter] = useState('all')
  const [requestTrip, setRequestTrip] = useState<typeof TRIPS[0]|null>(null)
  const [floatTrip,   setFloatTrip]   = useState<typeof TRIPS[0]|null>(null)
  const [reviewTrip,  setReviewTrip]  = useState<typeof TRIPS[0]|null>(null)
  const [showPost,    setShowPost]    = useState(false)

  const filtered = TRIPS.filter(t => typeFilter==='all' || t.type===typeFilter)

  return (
    <div>
      {/* Header */}
      <div style={{ background:'linear-gradient(160deg, #0F1A0F, #141F14)', border:'1px solid #243824', borderRadius:8, padding:'40px 38px 36px', marginBottom:10, position:'relative', overflow:'hidden' }}>
        <div style={{ position:'absolute', right:-60, top:-60, width:280, height:280, borderRadius:'50%', background:'radial-gradient(circle, rgba(200,146,42,0.07) 0%, transparent 70%)', pointerEvents:'none' }} />
        <div style={{ position:'relative', maxWidth:600 }}>
          <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:11, letterSpacing:4, color:B.copper, marginBottom:8 }}>SALTGRASS</div>
          <h1 style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:42, letterSpacing:1, color:B.bone, margin:'0 0 12px', textTransform:'uppercase', lineHeight:1 }}>CREW UP</h1>
          <p style={{ fontSize:14, color:B.parchment, maxWidth:540, lineHeight:1.8, margin:'0 0 6px' }}>
            Empty seat in the boat? Room in the truck? Post your trip and split the cost with a verified Saltgrass member.
          </p>
          <p style={{ fontSize:12, color:B.dust, maxWidth:520, lineHeight:1.7, margin:'0 0 24px' }}>
            Every member is phone-verified. Captains approve their own crew. Both sides rate after the trip. Float plan auto-generated — share it before you launch.
          </p>
          <div style={{ display:'flex', gap:10 }}>
            <button onClick={() => setShowPost(true)} style={{ background:B.copper, color:'#0A0C08', border:'none', borderRadius:4, padding:'12px 24px', fontFamily:'Impact,Arial Black,sans-serif', fontSize:13, letterSpacing:2, cursor:'pointer' }}>+ POST A TRIP</button>
            <button style={{ background:'transparent', color:B.parchment, border:`2px solid ${B.canopy}`, borderRadius:4, padding:'12px 20px', fontFamily:'Impact,Arial Black,sans-serif', fontSize:12, letterSpacing:2, cursor:'pointer' }}>📋 MY FLOAT PLANS</button>
          </div>
        </div>
      </div>

      {/* How it works */}
      <div style={{ display:'grid', gridTemplateColumns:'repeat(5, 1fr)', gap:8, marginBottom:10 }}>
        {[
          {n:'01', icon:'🔍', t:'FIND A TRIP',       d:'Browse by region. Read the captain\'s profile and past crew reviews.'},
          {n:'02', icon:'✅', t:'VERIFY IDENTITY',    d:'One-time phone verification. Captains see your profile before deciding.'},
          {n:'03', icon:'🤝', t:'MUTUAL ACCEPTANCE',  d:'Captain approves or declines. Both parties must agree before payment.'},
          {n:'04', icon:'📋', t:'GET FLOAT PLAN',     d:'Auto-generated on confirmation. Email it to someone on shore.'},
          {n:'05', icon:'⭐', t:'RATE EACH OTHER',    d:'Both sides rate after the trip. Keeps quality high and bad actors out.'},
        ].map(s => (
          <div key={s.n} style={{ background:B.forest, border:'1px solid #243824', borderRadius:8, padding:'14px 12px' }}>
            <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:22, color:B.canopy, marginBottom:6 }}>{s.n}</div>
            <div style={{ fontSize:18, marginBottom:6 }}>{s.icon}</div>
            <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:10, letterSpacing:2, color:B.copper, marginBottom:5 }}>{s.t}</div>
            <div style={{ fontSize:11, color:B.parchment, lineHeight:1.6 }}>{s.d}</div>
          </div>
        ))}
      </div>

      <div style={{ display:'grid', gridTemplateColumns:'1fr 220px', gap:10, alignItems:'start' }}>
        <div>
          <div style={{ display:'flex', gap:7, marginBottom:10 }}>
            {[['all','ALL TRIPS'],['fishing','🎣 FISHING'],['hunting','🏹 HUNTING']].map(([id,label]) => (
              <button key={id} onClick={() => setTypeFilter(id)} style={{ padding:'7px 14px', borderRadius:4, fontFamily:'Impact,Arial Black,sans-serif', fontSize:10, letterSpacing:2, cursor:'pointer', border:`2px solid ${typeFilter===id ? B.copper : B.canopy}`, background: typeFilter===id ? 'rgba(200,146,42,0.12)' : 'transparent', color: typeFilter===id ? B.copper : B.parchment }}>
                {label}
              </button>
            ))}
          </div>

          {filtered.map(trip => (
            <TripCard
              key={trip.id} trip={trip}
              onRequest={() => setRequestTrip(trip)}
              onFloat={() => setFloatTrip(trip)}
              onReview={() => setReviewTrip(trip)}
              isOwn={trip.captain === 'RiverRoller88'}
            />
          ))}
        </div>

        {/* Sidebar */}
        <div style={{ position:'sticky', top:72, display:'flex', flexDirection:'column', gap:10 }}>
          <div style={{ background:B.forest, borderRadius:8, padding:16, border:'1px solid #243824' }}>
            <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:10, letterSpacing:3, color:B.copper, marginBottom:10 }}>IDENTITY VERIFICATION</div>
            {[
              {icon:'📱', label:'Phone number', desc:'SMS verified US number required'},
              {icon:'📷', label:'Profile photo', desc:'Real face photo, no avatars'},
              {icon:'✅', label:'Real name',     desc:'Matches your Saltgrass profile'},
              {icon:'⭐', label:'Trip history',  desc:'Past trips and crew reviews visible'},
            ].map((v,i) => (
              <div key={v.label} style={{ display:'flex', gap:8, padding:'6px 0', borderBottom: i<3 ? `1px solid ${B.canopy}` : 'none' }}>
                <span style={{ fontSize:15, flexShrink:0 }}>{v.icon}</span>
                <div>
                  <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:10, letterSpacing:1, color:B.bone }}>{v.label}</div>
                  <div style={{ fontSize:10, color:B.dust }}>{v.desc}</div>
                </div>
              </div>
            ))}
          </div>

          <div style={{ background:B.forest, borderRadius:8, padding:16, border:'1px solid #243824' }}>
            <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:10, letterSpacing:3, color:B.copper, marginBottom:10 }}>HOW WE CHARGE</div>
            <div style={{ fontSize:12, color:B.parchment, lineHeight:1.7, marginBottom:8 }}>
              Saltgrass charges a <strong style={{ color:B.bone }}>10% platform fee</strong> added to the crew member's payment. Captains receive 100% of what they set.
            </div>
            <div style={{ fontSize:11, color:B.dust, lineHeight:1.6 }}>Payment held in escrow until trip completes. Full refund if captain cancels or trip doesn't happen.</div>
          </div>

          <div style={{ background:B.forest, borderRadius:8, padding:16, border:'1px solid #243824' }}>
            <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:10, letterSpacing:3, color:B.danger, marginBottom:10 }}>🛡️ SAFETY</div>
            <div style={{ fontSize:11, color:B.parchment, lineHeight:1.7, marginBottom:8 }}>Float plan auto-generated for every confirmed trip. Share it with someone on shore before departure.</div>
            <div style={{ fontSize:11, color:B.dust }}>Coast Guard: <strong style={{ color:B.bone }}>VHF Ch 16</strong><br/>Emergency: <strong style={{ color:B.bone }}>1-800-424-8802</strong></div>
          </div>

          <div style={{ background:B.forest, borderRadius:8, padding:16, border:'1px solid #243824' }}>
            <div style={{ fontFamily:'Impact,Arial Black,sans-serif', fontSize:10, letterSpacing:3, color:B.copper, marginBottom:10 }}>THE RULES</div>
            {['Verified members only','Captain controls the boat','Cost = fuel & access only','48hr cancellation forfeits seat','Rate honestly every trip','No alcohol before departure'].map((r,i) => (
              <div key={i} style={{ fontSize:11, color:B.parchment, padding:'4px 0', borderBottom: i<5 ? `1px solid ${B.canopy}` : 'none', display:'flex', gap:7 }}>
                <span style={{ color:B.copper, fontFamily:'Impact,Arial Black,sans-serif', fontSize:9, flexShrink:0 }}>{String(i+1).padStart(2,'0')}</span>
                <span>{r}</span>
              </div>
            ))}
          </div>

          <button onClick={() => setShowPost(true)} style={{ background:'transparent', color:B.copper, border:`2px solid ${B.copper}`, borderRadius:4, padding:'11px', fontFamily:'Impact,Arial Black,sans-serif', fontSize:11, letterSpacing:2, cursor:'pointer', width:'100%' }}>
            + POST YOUR TRIP
          </button>
        </div>
      </div>

      {requestTrip && <RequestModal trip={requestTrip} onClose={() => setRequestTrip(null)} />}
      {floatTrip   && <FloatPlan trip={floatTrip} crewNames={['FlatsDrifter']} onClose={() => setFloatTrip(null)} />}
      {reviewTrip  && <CaptainReviewModal trip={reviewTrip} onClose={() => setReviewTrip(null)} />}
      {showPost    && <PostTripModal onClose={() => setShowPost(false)} />}
    </div>
  )
}
