'use client'
// src/app/crewup/page.tsx

import { useState } from 'react'
import { REGIONS } from '@/lib/types'

const B = {
  bg:'#4A5240', surf:'#3D4535', card:'#333B2C',
  sun:'#E8DFC8', sil:'#1A1E14', sub:'#B8B49A',
  dust:'#8A866E', border:'rgba(232,223,200,0.10)',
  accent:'#D4982E', danger:'#C8452A', go:'#7AE07A',
}
const O = { fontFamily:"'Oswald', sans-serif" }

const CONVENIENCE_FEE = 2.99

const TRIPS = [
  { id:1, captain:'RiverRoller88', captain_rating:4.9, captain_trips:34, avatar:'🧔', verified_phone:true, type:'fishing', title:'Inshore Redfish — Pensacola Bay', description:'Half-day inshore Saturday at 5am. Targeting redfish and speckled trout on the Pensacola Bay flats. 22ft Pathfinder, 150 Yamaha. Light tackle provided. Back by noon.', region:'panhandle', region_icon:'🏖️', region_label:'Panhandle', departure:'Bayou Chico Boat Ramp, Pensacola, FL', destination:'Pensacola Bay Flats — North Shore', date:'Sat Jun 7, 2026', time:'5:00 AM', return_time:'12:00 PM', seats_total:3, seats_filled:1, cost_per_person:45, cost_covers:'Fuel + ramp fee split', vessel:'2021 Pathfinder 22 HPS', vessel_hin:'PFD22XYZ2021', tags:['Redfish','Speckled Trout','Inshore'], requestors:[{id:101,name:'FlatsDrifter',rating:4.8,trips:12,photo:'🎣',verified:true,bio:'Panhandle angler, 10 years on the water.',status:'pending'}] },
  { id:2, captain:'SwampBuckHunter', captain_rating:5.0, captain_trips:12, avatar:'🧢', verified_phone:true, type:'hunting', title:'Hog Hunt — Private Ranch, Ocala', description:'Friday night into Saturday morning on a 400-acre private ranch. Spot and stalk plus feeder stands. ATV access. .308 available if needed.', region:'centralfl', region_icon:'🐊', region_label:'Central Florida', departure:'Loves Truck Stop, I-75 Exit 358', destination:'Private Ranch — address after confirmation', date:'Fri Jun 6, 2026', time:'7:00 PM', return_time:'Sat Jun 7, 10:00 AM', seats_total:2, seats_filled:0, cost_per_person:60, cost_covers:'Gas + land access fee split', vessel:'F-250 + ATV trailer', vessel_hin:'N/A', tags:['Hog Hunting','Night Hunt','Private Land'], requestors:[] },
]

// ── Float Plan ───────────────────────────────────────────────
function FloatPlan({ trip, onClose }: { trip: typeof TRIPS[0]; onClose:()=>void }) {
  const [contact, setContact] = useState('')
  const [phone,   setPhone]   = useState('')
  const [copied,  setCopied]  = useState(false)

  const plan = `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SALTGRASS FLOAT PLAN
Generated: ${new Date().toLocaleString('en-US')}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

TRIP: ${trip.title}
CAPTAIN: @${trip.captain}
DATE: ${trip.date} at ${trip.time}
EXPECTED RETURN: ${trip.return_time}

VESSEL: ${trip.vessel}
HIN: ${trip.vessel_hin}
DEPARTURE: ${trip.departure}
DESTINATION: ${trip.destination}

SOULS ABOARD: ${trip.seats_filled + 1}

EMERGENCY CONTACT ON SHORE
Name: ${contact || '[FILL IN BEFORE DEPARTURE]'}
Phone: ${phone  || '[FILL IN BEFORE DEPARTURE]'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EMERGENCIES
US Coast Guard: VHF Channel 16
Coast Guard Hotline: 1-800-424-8802
Florida Marine Patrol: *FMP from cell
If not returned by ${trip.return_time} — call Coast Guard immediately
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by Saltgrass · saltgrass-3scu.vercel.app`

  return (
    <div style={{ position:'fixed',inset:0,background:'rgba(0,0,0,0.9)',zIndex:600,display:'flex',alignItems:'center',justifyContent:'center',padding:16,overflowY:'auto' }}>
      <div style={{ background:B.surf,borderRadius:8,padding:26,maxWidth:500,width:'100%',border:`1px solid ${B.border}`,maxHeight:'90vh',overflowY:'auto' }}>
        <div style={{ display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:18 }}>
          <div style={{ ...O,fontSize:18,letterSpacing:2,color:B.sun }}>FLOAT PLAN</div>
          <button onClick={onClose} style={{ background:B.card,border:'none',borderRadius:4,color:B.dust,padding:'6px 12px',cursor:'pointer' }}>✕</button>
        </div>
        <div style={{ background:'rgba(212,152,46,0.08)',border:`1px solid ${B.accent}33`,borderRadius:6,padding:'10px 14px',marginBottom:16,fontSize:12,color:B.sub,lineHeight:1.7 }}>
          <strong style={{ color:B.sun }}>File this with someone on shore before you launch.</strong> The Coast Guard recommends it every single time.
        </div>
        <div style={{ display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginBottom:14 }}>
          <div>
            <label style={{ ...O,fontSize:9,letterSpacing:2,color:B.dust,display:'block',marginBottom:5 }}>EMERGENCY CONTACT</label>
            <input value={contact} onChange={e=>setContact(e.target.value)} placeholder="Wife, buddy, family..."
              style={{ background:B.sil,border:`1.5px solid ${B.border}`,borderRadius:4,color:B.sun,fontSize:13,padding:'9px 12px',width:'100%',outline:'none',boxSizing:'border-box' as any }} />
          </div>
          <div>
            <label style={{ ...O,fontSize:9,letterSpacing:2,color:B.dust,display:'block',marginBottom:5 }}>THEIR PHONE</label>
            <input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="(850) 555-0100"
              style={{ background:B.sil,border:`1.5px solid ${B.border}`,borderRadius:4,color:B.sun,fontSize:13,padding:'9px 12px',width:'100%',outline:'none',boxSizing:'border-box' as any }} />
          </div>
        </div>
        <div style={{ background:B.sil,borderRadius:4,padding:14,marginBottom:14,fontFamily:'monospace',fontSize:11,color:B.sub,lineHeight:1.8,whiteSpace:'pre-line',border:`1px solid ${B.border}`,maxHeight:260,overflowY:'auto' }}>
          {plan}
        </div>
        <div style={{ background:'rgba(200,69,42,0.08)',border:`1px solid ${B.danger}44`,borderRadius:6,padding:'10px 14px',marginBottom:14,fontSize:11,color:B.sub,lineHeight:1.6 }}>
          <strong style={{ ...O,fontSize:9,letterSpacing:2,color:B.danger }}>COAST GUARD</strong><br/>
          VHF Channel 16 · <strong style={{ color:B.sun }}>1-800-424-8802</strong> · Florida Marine Patrol: <strong style={{ color:B.sun }}>*FMP</strong>
        </div>
        <div style={{ display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:8 }}>
          {[{l:copied?'✓ COPIED':'📋 COPY',a:()=>{navigator.clipboard.writeText(plan);setCopied(true);setTimeout(()=>setCopied(false),2500)}},
            {l:'📧 EMAIL',a:()=>window.open(`mailto:?subject=${encodeURIComponent('Float Plan — '+trip.title)}&body=${encodeURIComponent(plan)}`)},
            {l:'🖨️ PRINT', a:()=>window.print()}].map(b=>(
            <button key={b.l} onClick={b.a} style={{ background:B.card,color:B.sun,border:`1px solid ${B.border}`,borderRadius:4,padding:'10px',...O,fontSize:10,letterSpacing:1,cursor:'pointer' }}>{b.l}</button>
          ))}
        </div>
      </div>
    </div>
  )
}

// ── Request Seat Modal ───────────────────────────────────────
function RequestModal({ trip, onClose }: { trip: typeof TRIPS[0]; onClose:()=>void }) {
  const [step,  setStep]  = useState(1)
  const [vStep, setVStep] = useState(1)
  const [phone, setPhone] = useState('')
  const [code,  setCode]  = useState('')
  const [note,  setNote]  = useState('')

  return (
    <div style={{ position:'fixed',inset:0,background:'rgba(0,0,0,0.9)',zIndex:600,display:'flex',alignItems:'center',justifyContent:'center',padding:16 }}>
      <div style={{ background:B.surf,borderRadius:8,padding:28,maxWidth:460,width:'100%',border:`1px solid ${B.border}` }}>
        <div style={{ display:'flex',gap:6,marginBottom:20 }}>
          {['VERIFY','REVIEW','CONFIRM'].map((s,i)=>(
            <div key={s} style={{ flex:1 }}>
              <div style={{ height:3,borderRadius:2,background:i+1<=step?B.accent:B.border,marginBottom:4 }} />
              <div style={{ ...O,fontSize:8,letterSpacing:1,color:i+1<=step?B.accent:B.dust,textAlign:'center' }}>{s}</div>
            </div>
          ))}
        </div>

        {step===1 && (
          <div>
            <div style={{ ...O,fontSize:16,letterSpacing:2,color:B.sun,marginBottom:6 }}>VERIFY YOUR IDENTITY</div>
            <p style={{ fontSize:12,color:B.sub,lineHeight:1.7,marginBottom:18 }}>The captain needs to know who's getting on their boat. Phone verification required.</p>
            {vStep===1 && (
              <div>
                <div style={{ background:B.card,borderRadius:6,padding:'12px 14px',marginBottom:14,border:`1px solid ${B.border}` }}>
                  {[{icon:'📱',l:'Phone verified',d:'Real US number'},{icon:'📷',l:'Profile photo',d:'Real face, no avatars'},{icon:'⭐',l:'Trip history',d:'Past trips and reviews visible'}].map((v,i)=>(
                    <div key={v.l} style={{ display:'flex',gap:10,padding:'6px 0',borderBottom:i<2?`1px solid ${B.border}`:'none' }}>
                      <span style={{ fontSize:15,flexShrink:0 }}>{v.icon}</span>
                      <div><div style={{ ...O,fontSize:10,letterSpacing:1,color:B.sun }}>{v.l}</div><div style={{ fontSize:11,color:B.dust }}>{v.d}</div></div>
                    </div>
                  ))}
                </div>
                <button onClick={()=>setVStep(2)} style={{ width:'100%',background:B.accent,color:B.sil,border:'none',borderRadius:4,padding:'12px',...O,fontSize:13,fontWeight:600,letterSpacing:2,cursor:'pointer' }}>VERIFY PHONE →</button>
              </div>
            )}
            {vStep===2 && (
              <div>
                <label style={{ ...O,fontSize:9,letterSpacing:2,color:B.dust,display:'block',marginBottom:5 }}>YOUR PHONE</label>
                <input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="(850) 555-0100" type="tel"
                  style={{ background:B.sil,border:`1.5px solid ${B.border}`,borderRadius:4,color:B.sun,fontSize:15,padding:'11px 14px',width:'100%',outline:'none',boxSizing:'border-box' as any,marginBottom:12 }} />
                <button onClick={()=>setVStep(3)} style={{ width:'100%',background:B.accent,color:B.sil,border:'none',borderRadius:4,padding:'12px',...O,fontSize:13,fontWeight:600,letterSpacing:2,cursor:'pointer' }}>SEND CODE</button>
              </div>
            )}
            {vStep===3 && (
              <div>
                <div style={{ ...O,fontSize:12,letterSpacing:2,color:B.sun,marginBottom:4 }}>ENTER CODE</div>
                <div style={{ fontSize:12,color:B.dust,marginBottom:12 }}>Sent to {phone}</div>
                <input value={code} onChange={e=>setCode(e.target.value)} maxLength={6} placeholder="000000"
                  style={{ background:B.sil,border:`1.5px solid ${B.border}`,borderRadius:4,color:B.accent,fontSize:28,fontWeight:700,padding:'12px',width:'100%',outline:'none',boxSizing:'border-box' as any,textAlign:'center',letterSpacing:10,marginBottom:14 }} />
                <button onClick={()=>{if(code.length===6)setStep(2)}} style={{ width:'100%',background:code.length===6?B.accent:B.border,color:code.length===6?B.sil:B.dust,border:'none',borderRadius:4,padding:'12px',...O,fontSize:13,fontWeight:600,letterSpacing:2,cursor:code.length===6?'pointer':'not-allowed' }}>CONFIRM →</button>
              </div>
            )}
          </div>
        )}

        {step===2 && (
          <div>
            <div style={{ ...O,fontSize:16,letterSpacing:2,color:B.sun,marginBottom:14 }}>REVIEW & REQUEST</div>
            <div style={{ background:B.card,borderRadius:6,padding:13,marginBottom:14,border:`1px solid ${B.border}` }}>
              <div style={{ ...O,fontSize:13,color:B.sun,marginBottom:5 }}>{trip.title}</div>
              <div style={{ display:'grid',gridTemplateColumns:'1fr 1fr',gap:'4px 14px',fontSize:11,color:B.sub }}>
                <div>📅 {trip.date}</div><div>⏰ {trip.time}</div>
                <div>📍 {trip.departure.split(',')[0]}</div><div>⛵ {trip.vessel.split(' ').slice(0,3).join(' ')}</div>
              </div>
            </div>

            <div style={{ background:B.sil,borderRadius:4,padding:'11px 13px',marginBottom:14,border:`1px solid ${B.border}` }}>
              <div style={{ ...O,fontSize:9,letterSpacing:2,color:B.dust,marginBottom:8 }}>COST BREAKDOWN</div>
              {[
                { label:`Your share (${trip.cost_covers})`,  val:`$${trip.cost_per_person}` },
                { label:'Saltgrass convenience fee',          val:`$${CONVENIENCE_FEE}` },
              ].map((r,i)=>(
                <div key={i} style={{ display:'flex',justifyContent:'space-between',padding:'4px 0',borderBottom:`1px solid ${B.border}` }}>
                  <span style={{ fontSize:12,color:B.sub }}>{r.label}</span>
                  <span style={{ fontSize:12,color:B.sun,fontWeight:700 }}>{r.val}</span>
                </div>
              ))}
              <div style={{ display:'flex',justifyContent:'space-between',paddingTop:8 }}>
                <span style={{ ...O,fontSize:12,letterSpacing:1,color:B.sun }}>TOTAL</span>
                <span style={{ ...O,fontSize:20,color:B.accent }}>${(trip.cost_per_person+CONVENIENCE_FEE).toFixed(2)}</span>
              </div>
              <div style={{ fontSize:10,color:B.dust,marginTop:6,lineHeight:1.6 }}>
                The $2.99 convenience fee covers secure matching, identity verification, and float plan generation. Captain is not charged.
              </div>
            </div>

            <div style={{ marginBottom:14 }}>
              <label style={{ ...O,fontSize:9,letterSpacing:2,color:B.dust,display:'block',marginBottom:5 }}>NOTE TO CAPTAIN</label>
              <textarea value={note} onChange={e=>setNote(e.target.value)} rows={3}
                placeholder="Introduce yourself — experience level, what you fish, why you want to join..."
                style={{ background:B.sil,border:`1.5px solid ${B.border}`,borderRadius:4,color:B.sun,fontSize:13,padding:'10px 12px',width:'100%',outline:'none',resize:'none' as any,boxSizing:'border-box' as any,fontFamily:'Inter,sans-serif',lineHeight:1.6 }} />
            </div>

            <div style={{ background:'rgba(212,152,46,0.08)',border:`1px solid ${B.accent}33`,borderRadius:6,padding:'10px 14px',marginBottom:14,fontSize:11,color:B.sub,lineHeight:1.6 }}>
              📋 Float plan auto-generated when captain confirms. Your $2.99 is charged now. Trip cost paid to captain directly.
            </div>

            <div style={{ display:'flex',gap:8 }}>
              <button onClick={()=>setStep(1)} style={{ flex:1,padding:'11px',background:'transparent',border:`1.5px solid ${B.border}`,borderRadius:4,color:B.sub,...O,fontSize:11,letterSpacing:1,cursor:'pointer' }}>← BACK</button>
              <button onClick={()=>setStep(3)} style={{ flex:2,background:B.accent,color:B.sil,border:'none',borderRadius:4,padding:'12px',...O,fontSize:12,fontWeight:600,letterSpacing:1,cursor:'pointer' }}>
                SEND REQUEST — ${(trip.cost_per_person+CONVENIENCE_FEE).toFixed(2)}
              </button>
            </div>
          </div>
        )}

        {step===3 && (
          <div style={{ textAlign:'center',padding:'10px 0' }}>
            <div style={{ fontSize:52,marginBottom:14 }}>⛵</div>
            <div style={{ ...O,fontSize:18,letterSpacing:2,color:B.sun,marginBottom:8 }}>REQUEST SENT!</div>
            <div style={{ fontSize:13,color:B.sub,lineHeight:1.8,marginBottom:16 }}>
              @{trip.captain} will review your profile and respond within 24 hours. Float plan sent to both parties after confirmation.
            </div>
            <div style={{ background:B.card,borderRadius:6,padding:14,marginBottom:18,textAlign:'left',border:`1px solid ${B.border}` }}>
              <div style={{ ...O,fontSize:9,letterSpacing:2,color:B.accent,marginBottom:8 }}>WHAT HAPPENS NEXT</div>
              {[
                {n:'1️⃣',t:`@${trip.captain} reviews your profile and accepts or declines`},
                {n:'2️⃣',t:'Accepted — float plan emailed to both parties'},
                {n:'3️⃣',t:'You pay the captain directly for your share on the day'},
                {n:'4️⃣',t:'Both sides rate each other after the trip'},
              ].map(s=>(
                <div key={s.n} style={{ display:'flex',gap:10,padding:'5px 0',fontSize:12,color:B.sub }}>
                  <span>{s.n}</span><span>{s.t}</span>
                </div>
              ))}
            </div>
            <button onClick={onClose} style={{ background:B.accent,color:B.sil,border:'none',borderRadius:4,padding:'12px 28px',...O,fontSize:13,letterSpacing:2,cursor:'pointer' }}>DONE</button>
          </div>
        )}
        {step<3 && <button onClick={onClose} style={{ width:'100%',marginTop:12,background:'none',border:'none',color:B.dust,fontSize:12,cursor:'pointer' }}>Cancel</button>}
      </div>
    </div>
  )
}

// ── Captain Review Modal ─────────────────────────────────────
function CaptainReviewModal({ trip, onClose }: { trip: typeof TRIPS[0]; onClose:()=>void }) {
  const [decisions, setDecisions] = useState<Record<number,string>>({})
  return (
    <div style={{ position:'fixed',inset:0,background:'rgba(0,0,0,0.9)',zIndex:600,display:'flex',alignItems:'center',justifyContent:'center',padding:16 }}>
      <div style={{ background:B.surf,borderRadius:8,padding:26,maxWidth:480,width:'100%',border:`1px solid ${B.border}`,maxHeight:'90vh',overflowY:'auto' }}>
        <div style={{ display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:18 }}>
          <div style={{ ...O,fontSize:16,letterSpacing:2,color:B.sun }}>REVIEW REQUESTS</div>
          <button onClick={onClose} style={{ background:B.card,border:'none',borderRadius:4,color:B.dust,padding:'6px 12px',cursor:'pointer' }}>✕</button>
        </div>
        <div style={{ background:B.card,borderRadius:6,padding:'10px 14px',marginBottom:14,fontSize:12,color:B.sub,lineHeight:1.6 }}>
          You control who gets on your boat. Accept or decline — declined members are notified politely.
        </div>
        {trip.requestors.length===0 ? (
          <div style={{ textAlign:'center',padding:'30px 0',color:B.dust,fontSize:13 }}>No requests yet.</div>
        ) : trip.requestors.map(r=>(
          <div key={r.id} style={{ background:B.card,borderRadius:6,padding:14,marginBottom:12,border:`1px solid ${decisions[r.id]==='accept'?'rgba(122,224,122,0.3)':decisions[r.id]==='decline'?`${B.danger}44`:B.border}` }}>
            <div style={{ display:'flex',gap:12,marginBottom:10 }}>
              <div style={{ width:44,height:44,borderRadius:'50%',background:B.surf,display:'flex',alignItems:'center',justifyContent:'center',fontSize:20,flexShrink:0 }}>{r.photo}</div>
              <div style={{ flex:1 }}>
                <div style={{ ...O,fontSize:14,color:B.sun }}>@{r.name}</div>
                <div style={{ display:'flex',gap:8,alignItems:'center',marginTop:2 }}>
                  <span style={{ color:B.accent,fontSize:11 }}>{'★'.repeat(Math.floor(r.rating))}</span>
                  <span style={{ fontSize:11,color:B.dust }}>{r.rating} · {r.trips} trips</span>
                  {r.verified && <span style={{ background:'rgba(212,152,46,0.2)',color:B.accent,borderRadius:3,padding:'1px 6px',...O,fontSize:8,letterSpacing:1 }}>✓ VERIFIED</span>}
                </div>
              </div>
            </div>
            <div style={{ fontSize:12,color:B.sub,lineHeight:1.6,marginBottom:12 }}>{r.bio}</div>
            {!decisions[r.id] ? (
              <div style={{ display:'grid',gridTemplateColumns:'1fr 1fr',gap:8 }}>
                <button onClick={()=>setDecisions(d=>({...d,[r.id]:'accept'}))} style={{ background:'rgba(61,122,61,0.3)',color:B.go,border:'1px solid rgba(122,224,122,0.3)',borderRadius:4,padding:'10px',...O,fontSize:11,letterSpacing:1,cursor:'pointer' }}>✓ ACCEPT</button>
                <button onClick={()=>setDecisions(d=>({...d,[r.id]:'decline'}))} style={{ background:'rgba(200,69,42,0.2)',color:'#E07A7A',border:`1px solid ${B.danger}44`,borderRadius:4,padding:'10px',...O,fontSize:11,letterSpacing:1,cursor:'pointer' }}>✕ DECLINE</button>
              </div>
            ) : (
              <div style={{ textAlign:'center',padding:'8px',borderRadius:4,background:decisions[r.id]==='accept'?'rgba(61,122,61,0.15)':'rgba(200,69,42,0.12)',border:`1px solid ${decisions[r.id]==='accept'?'rgba(122,224,122,0.2)':B.danger+'44'}` }}>
                <span style={{ ...O,fontSize:11,letterSpacing:1,color:decisions[r.id]==='accept'?B.go:'#E07A7A' }}>
                  {decisions[r.id]==='accept'?'✓ ACCEPTED — Float plan will be sent':'✕ DECLINED — Member will be notified'}
                </span>
              </div>
            )}
          </div>
        ))}
        <button onClick={onClose} style={{ width:'100%',marginTop:6,background:B.accent,color:B.sil,border:'none',borderRadius:4,padding:'12px',...O,fontSize:13,letterSpacing:2,cursor:'pointer' }}>SAVE DECISIONS</button>
      </div>
    </div>
  )
}

// ── Post Trip Modal ──────────────────────────────────────────
function PostTripModal({ onClose }: { onClose:()=>void }) {
  const [form, setForm] = useState({ type:'fishing',title:'',description:'',region_id:'',departure:'',destination:'',date:'',time:'',return_time:'',seats:'2',cost_per_person:'',cost_covers:'',vessel:'' })
  const set = (k:string,v:string) => setForm(f=>({...f,[k]:v}))
  const costNum = Number(form.cost_per_person)||0
  const crewFee = costNum>0 ? (costNum+CONVENIENCE_FEE).toFixed(2) : '—'

  return (
    <div style={{ position:'fixed',inset:0,background:'rgba(0,0,0,0.9)',zIndex:600,display:'flex',alignItems:'center',justifyContent:'center',padding:16 }}>
      <div style={{ background:B.surf,borderRadius:8,padding:26,maxWidth:540,width:'100%',border:`1px solid ${B.border}`,maxHeight:'90vh',overflowY:'auto' }}>
        <div style={{ display:'flex',justifyContent:'space-between',marginBottom:20 }}>
          <div style={{ ...O,fontSize:18,letterSpacing:2,color:B.sun }}>POST A TRIP</div>
          <button onClick={onClose} style={{ background:B.card,border:'none',borderRadius:4,color:B.dust,padding:'6px 12px',cursor:'pointer' }}>✕</button>
        </div>
        <div style={{ display:'flex',flexDirection:'column',gap:13 }}>
          <div style={{ display:'grid',gridTemplateColumns:'1fr 1fr',gap:8 }}>
            {[['fishing','🎣 FISHING'],['hunting','🏹 HUNTING']].map(([id,label])=>(
              <button key={id} type="button" onClick={()=>set('type',id)} style={{ padding:'11px',borderRadius:4,border:`2px solid ${form.type===id?B.accent:B.border}`,background:form.type===id?'rgba(212,152,46,0.12)':'transparent',color:form.type===id?B.accent:B.sub,...O,fontSize:13,letterSpacing:2,cursor:'pointer' }}>{label}</button>
            ))}
          </div>
          {[
            {k:'title',     l:'TRIP TITLE',           p:'Inshore Redfish — Pensacola Bay'},
            {k:'departure', l:'MEET / DEPARTURE',      p:'Bayou Chico Boat Ramp, Pensacola FL'},
            {k:'destination',l:"WHERE YOU'RE HEADED",  p:'Pensacola Bay North Flats'},
            {k:'vessel',    l:'VESSEL OR VEHICLE',     p:'2021 Pathfinder 22 HPS'},
            {k:'cost_covers',l:'COST COVERS',          p:'Fuel + ramp fee'},
          ].map(({k,l,p})=>(
            <div key={k}>
              <label style={{ ...O,fontSize:9,letterSpacing:2,color:B.dust,display:'block',marginBottom:5 }}>{l}</label>
              <input value={(form as any)[k]} onChange={e=>set(k,e.target.value)} placeholder={p}
                style={{ background:B.sil,border:`1.5px solid ${B.border}`,borderRadius:4,color:B.sun,fontSize:13,padding:'10px 12px',width:'100%',outline:'none',boxSizing:'border-box' as any }} />
            </div>
          ))}
          <div style={{ display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:10 }}>
            {[['date','DATE','date'],['time','DEPARTS','time'],['return_time','RETURNS','time']].map(([k,l,t])=>(
              <div key={k}>
                <label style={{ ...O,fontSize:9,letterSpacing:2,color:B.dust,display:'block',marginBottom:5 }}>{l}</label>
                <input type={t} value={(form as any)[k]} onChange={e=>set(k,e.target.value)}
                  style={{ background:B.sil,border:`1.5px solid ${B.border}`,borderRadius:4,color:B.sun,fontSize:12,padding:'10px',width:'100%',outline:'none',boxSizing:'border-box' as any }} />
              </div>
            ))}
          </div>
          <div style={{ display:'grid',gridTemplateColumns:'1fr 1fr',gap:10 }}>
            <div>
              <label style={{ ...O,fontSize:9,letterSpacing:2,color:B.dust,display:'block',marginBottom:5 }}>OPEN SEATS</label>
              <select value={form.seats} onChange={e=>set('seats',e.target.value)} style={{ background:B.sil,border:`1.5px solid ${B.border}`,borderRadius:4,color:B.sun,fontSize:13,padding:'10px 12px',width:'100%',outline:'none',cursor:'pointer' }}>
                {['1','2','3','4','5','6'].map(n=><option key={n} value={n}>{n} seat{Number(n)!==1?'s':''}</option>)}
              </select>
            </div>
            <div>
              <label style={{ ...O,fontSize:9,letterSpacing:2,color:B.dust,display:'block',marginBottom:5 }}>YOUR COST SHARE / SEAT ($)</label>
              <input type="number" value={form.cost_per_person} onChange={e=>set('cost_per_person',e.target.value)} placeholder="45"
                style={{ background:B.sil,border:`1.5px solid ${B.border}`,borderRadius:4,color:B.sun,fontSize:18,fontWeight:700,padding:'10px 12px',width:'100%',outline:'none',boxSizing:'border-box' as any }} />
            </div>
          </div>

          {costNum>0 && (
            <div style={{ background:B.card,borderRadius:4,padding:'10px 13px',border:`1px solid ${B.border}`,fontSize:11,color:B.sub,lineHeight:1.7 }}>
              Crew members pay <strong style={{ color:B.accent }}>${crewFee}</strong> each — your ${costNum} + $2.99 Saltgrass convenience fee.<br/>
              <strong style={{ color:B.sun }}>You post free.</strong> The $2.99 is charged to crew, not you.
            </div>
          )}

          <div>
            <label style={{ ...O,fontSize:9,letterSpacing:2,color:B.dust,display:'block',marginBottom:5 }}>REGION</label>
            <select value={form.region_id} onChange={e=>set('region_id',e.target.value)} style={{ background:B.sil,border:`1.5px solid ${B.border}`,borderRadius:4,color:form.region_id?B.sun:B.dust,fontSize:13,padding:'10px 12px',width:'100%',outline:'none',cursor:'pointer' }}>
              <option value="">Select region...</option>
              {REGIONS.map(r=><option key={r.id} value={r.id}>{r.icon} {r.label}</option>)}
            </select>
          </div>
          <div>
            <label style={{ ...O,fontSize:9,letterSpacing:2,color:B.dust,display:'block',marginBottom:5 }}>TRIP DETAILS</label>
            <textarea value={form.description} onChange={e=>set('description',e.target.value)} rows={3}
              placeholder="Target species, experience level needed, what to bring, what's included..."
              style={{ background:B.sil,border:`1.5px solid ${B.border}`,borderRadius:4,color:B.sun,fontSize:13,padding:'10px 12px',width:'100%',outline:'none',resize:'none' as any,boxSizing:'border-box' as any,fontFamily:'Inter,sans-serif',lineHeight:1.6 }} />
          </div>
          <div style={{ background:'rgba(212,152,46,0.08)',border:`1px solid ${B.accent}33`,borderRadius:6,padding:'10px 14px',fontSize:11,color:B.sub,lineHeight:1.6 }}>
            📋 <strong style={{ color:B.sun }}>Float plan auto-generated</strong> when you confirm a crew member.
          </div>
          <button onClick={onClose} style={{ width:'100%',background:B.accent,color:B.sil,border:'none',borderRadius:4,padding:'13px',...O,fontSize:14,letterSpacing:2,cursor:'pointer' }}>
            POST TRIP — FREE
          </button>
        </div>
      </div>
    </div>
  )
}

// ── Trip Card ────────────────────────────────────────────────
function TripCard({ trip, onRequest, onFloat, onReview, isOwn }: { trip:typeof TRIPS[0]; onRequest:()=>void; onFloat:()=>void; onReview:()=>void; isOwn?:boolean }) {
  const seatsLeft = trip.seats_total - trip.seats_filled
  const total = trip.cost_per_person + CONVENIENCE_FEE

  return (
    <div style={{ background:B.card,border:`1px solid ${B.border}`,borderRadius:8,overflow:'hidden',marginBottom:10 }}>
      <div style={{ background:trip.type==='fishing'?'#0F1A2A':'#1A2B1A',padding:'7px 16px',display:'flex',justifyContent:'space-between',alignItems:'center' }}>
        <span style={{ ...O,fontSize:10,letterSpacing:3,color:trip.type==='fishing'?'#5A9FD4':B.accent }}>
          {trip.type==='fishing'?'🎣 FISHING':'🏹 HUNTING'}
        </span>
        <div style={{ display:'flex',gap:8,alignItems:'center' }}>
          <span style={{ fontSize:10,color:B.dust }}>{trip.region_icon} {trip.region_label}</span>
          {trip.verified_phone && <span style={{ background:'rgba(212,152,46,0.2)',color:B.accent,borderRadius:3,padding:'1px 7px',...O,fontSize:8,letterSpacing:1 }}>✓ VERIFIED</span>}
        </div>
      </div>
      <div style={{ padding:'15px 17px' }}>
        <div style={{ display:'flex',gap:12,marginBottom:12,alignItems:'flex-start' }}>
          <div style={{ width:42,height:42,borderRadius:'50%',background:B.surf,display:'flex',alignItems:'center',justifyContent:'center',fontSize:20,flexShrink:0 }}>{trip.avatar}</div>
          <div style={{ flex:1 }}>
            <div style={{ fontWeight:700,fontSize:13,color:B.sun }}>@{trip.captain}</div>
            <div style={{ display:'flex',gap:8,alignItems:'center' }}>
              <span style={{ color:B.accent,fontSize:11 }}>{'★'.repeat(Math.floor(trip.captain_rating))}</span>
              <span style={{ fontSize:10,color:B.dust }}>{trip.captain_rating} · {trip.captain_trips} trips · 📱 verified</span>
            </div>
          </div>
          <div style={{ textAlign:'right',flexShrink:0 }}>
            <div style={{ ...O,fontSize:19,color:B.accent }}>${total.toFixed(2)}</div>
            <div style={{ fontSize:9,color:B.dust }}>per person</div>
            <div style={{ fontSize:9,color:B.dust }}>(incl. $2.99 fee)</div>
          </div>
        </div>
        <div style={{ ...O,fontSize:15,letterSpacing:1,color:B.sun,marginBottom:5 }}>{trip.title}</div>
        <div style={{ fontSize:12,color:B.sub,lineHeight:1.7,marginBottom:12,overflow:'hidden',display:'-webkit-box',WebkitLineClamp:2,WebkitBoxOrient:'vertical' as any }}>{trip.description}</div>
        <div style={{ display:'grid',gridTemplateColumns:'1fr 1fr',gap:6,marginBottom:12 }}>
          {[['📅','DATE',trip.date],['⏰','DEPARTS',trip.time],['📍','MEET AT',trip.departure.split(',')[0]],['⛵','VESSEL',trip.vessel.split(' ').slice(0,3).join(' ')]].map(([icon,label,val])=>(
            <div key={String(label)} style={{ background:B.surf,borderRadius:3,padding:'7px 9px' }}>
              <div style={{ ...O,fontSize:8,letterSpacing:2,color:B.dust,marginBottom:2 }}>{icon} {label}</div>
              <div style={{ fontSize:11,color:B.sun,fontWeight:600 }}>{val}</div>
            </div>
          ))}
        </div>
        <div style={{ marginBottom:12 }}>
          <div style={{ display:'flex',justifyContent:'space-between',marginBottom:4 }}>
            <div style={{ ...O,fontSize:9,letterSpacing:2,color:B.dust }}>SEATS</div>
            <div style={{ ...O,fontSize:11,color:seatsLeft===0?B.danger:B.accent }}>{seatsLeft===0?'FULL':`${seatsLeft} LEFT`}</div>
          </div>
          <div style={{ height:5,background:B.border,borderRadius:3,overflow:'hidden' }}>
            <div style={{ height:'100%',width:`${(trip.seats_filled/trip.seats_total)*100}%`,background:seatsLeft===0?B.danger:B.accent,borderRadius:3 }} />
          </div>
        </div>
        <div style={{ display:'flex',gap:6,flexWrap:'wrap',marginBottom:12 }}>
          {trip.tags.map(t=><span key={t} style={{ background:B.surf,color:B.sub,borderRadius:3,padding:'2px 8px',fontSize:10 }}>#{t}</span>)}
        </div>
        <div style={{ display:'flex',gap:7 }}>
          <button onClick={onFloat} style={{ flex:1,background:'transparent',color:B.sub,border:`1.5px solid ${B.border}`,borderRadius:4,padding:'9px',...O,fontSize:9,letterSpacing:1,cursor:'pointer' }}>📋 FLOAT PLAN</button>
          {isOwn ? (
            <button onClick={onReview} style={{ flex:2,background:B.accent,color:B.sil,border:'none',borderRadius:4,padding:'9px',...O,fontSize:11,letterSpacing:1,cursor:'pointer' }}>
              REVIEW REQUESTS {trip.requestors.length>0&&<span style={{ background:B.danger,color:'#fff',borderRadius:'50%',width:16,height:16,fontSize:9,fontWeight:800,display:'inline-flex',alignItems:'center',justifyContent:'center',marginLeft:6 }}>{trip.requestors.length}</span>}
            </button>
          ) : (
            <button onClick={onRequest} disabled={seatsLeft===0} style={{ flex:2,background:seatsLeft===0?B.border:B.accent,color:seatsLeft===0?B.dust:B.sil,border:'none',borderRadius:4,padding:'9px',...O,fontSize:11,letterSpacing:1,cursor:seatsLeft===0?'not-allowed':'pointer' }}>
              {seatsLeft===0?'TRIP FULL':`REQUEST SEAT — $${total.toFixed(2)}`}
            </button>
          )}
        </div>
      </div>
    </div>
  )
}

// ── Main Page ────────────────────────────────────────────────
export default function CrewUpPage() {
  const [typeFilter,  setTypeFilter]  = useState('all')
  const [requestTrip, setRequestTrip] = useState<typeof TRIPS[0]|null>(null)
  const [floatTrip,   setFloatTrip]   = useState<typeof TRIPS[0]|null>(null)
  const [reviewTrip,  setReviewTrip]  = useState<typeof TRIPS[0]|null>(null)
  const [showPost,    setShowPost]    = useState(false)
  const filtered = TRIPS.filter(t=>typeFilter==='all'||t.type===typeFilter)

  return (
    <div>
      <div style={{ background:'linear-gradient(160deg,#333B2C,#3D4535)',border:`1px solid ${B.border}`,borderRadius:8,padding:'40px 38px 36px',marginBottom:10,position:'relative',overflow:'hidden' }}>
        <div style={{ position:'absolute',right:-60,top:-60,width:280,height:280,borderRadius:'50%',background:'radial-gradient(circle,rgba(212,152,46,0.06) 0%,transparent 70%)',pointerEvents:'none' }} />
        <div style={{ position:'relative',maxWidth:600 }}>
          <div style={{ ...O,fontSize:10,letterSpacing:4,color:B.accent,marginBottom:8 }}>SALTGRASS</div>
          <h1 style={{ ...O,fontSize:40,letterSpacing:1,color:B.sun,margin:'0 0 12px',textTransform:'uppercase',lineHeight:1 }}>CREW UP</h1>
          <p style={{ fontSize:14,color:B.sub,maxWidth:540,lineHeight:1.8,margin:'0 0 6px' }}>
            Empty seat in the boat? Room in the truck? Post your trip free and split the cost with a verified member.
          </p>
          <p style={{ fontSize:12,color:B.dust,maxWidth:520,lineHeight:1.7,margin:'0 0 24px' }}>
            Free to post. Crew members pay a $2.99 convenience fee when they request a seat. Captain is never charged.
          </p>
          <div style={{ display:'flex',gap:10 }}>
            <button onClick={()=>setShowPost(true)} style={{ background:B.accent,color:B.sil,border:'none',borderRadius:4,padding:'12px 24px',...O,fontSize:13,fontWeight:600,letterSpacing:2,cursor:'pointer' }}>+ POST A TRIP — FREE</button>
            <button style={{ background:'transparent',color:B.sub,border:`2px solid ${B.border}`,borderRadius:4,padding:'12px 20px',...O,fontSize:12,letterSpacing:2,cursor:'pointer' }}>📋 MY FLOAT PLANS</button>
          </div>
        </div>
      </div>

      <div style={{ display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:8,marginBottom:10 }}>
        {[
          {n:'01',icon:'🔍',t:'FIND A TRIP',      d:"Browse by region. Read the captain's profile and reviews."},
          {n:'02',icon:'✅',t:'VERIFY IDENTITY',   d:'One-time phone verify. Captain sees your profile before deciding.'},
          {n:'03',icon:'🤝',t:'MUTUAL ACCEPTANCE', d:'Captain approves or declines. Both parties agree before anything happens.'},
          {n:'04',icon:'📋',t:'GET FLOAT PLAN',    d:'Auto-generated on confirmation. Email to someone on shore.'},
          {n:'05',icon:'⭐',t:'RATE EACH OTHER',   d:'Both sides rate after. Keeps quality high.'},
        ].map(s=>(
          <div key={s.n} style={{ background:B.card,border:`1px solid ${B.border}`,borderRadius:8,padding:'14px 12px' }}>
            <div style={{ ...O,fontSize:22,color:B.border,marginBottom:6 }}>{s.n}</div>
            <div style={{ fontSize:18,marginBottom:6 }}>{s.icon}</div>
            <div style={{ ...O,fontSize:10,letterSpacing:2,color:B.accent,marginBottom:5 }}>{s.t}</div>
            <div style={{ fontSize:11,color:B.sub,lineHeight:1.6 }}>{s.d}</div>
          </div>
        ))}
      </div>

      <div style={{ display:'grid',gridTemplateColumns:'1fr 220px',gap:10,alignItems:'start' }}>
        <div>
          <div style={{ display:'flex',gap:7,marginBottom:10 }}>
            {[['all','ALL TRIPS'],['fishing','🎣 FISHING'],['hunting','🏹 HUNTING']].map(([id,label])=>(
              <button key={id} onClick={()=>setTypeFilter(id)} style={{ padding:'7px 14px',borderRadius:3,...O,fontSize:10,letterSpacing:2,cursor:'pointer',border:`2px solid ${typeFilter===id?B.accent:B.border}`,background:typeFilter===id?'rgba(212,152,46,0.12)':'transparent',color:typeFilter===id?B.accent:B.sub }}>
                {label}
              </button>
            ))}
          </div>
          {filtered.map(trip=>(
            <TripCard key={trip.id} trip={trip}
              onRequest={()=>setRequestTrip(trip)}
              onFloat={()=>setFloatTrip(trip)}
              onReview={()=>setReviewTrip(trip)}
              isOwn={trip.captain==='RiverRoller88'}
            />
          ))}
        </div>

        <div style={{ position:'sticky',top:72,display:'flex',flexDirection:'column',gap:10 }}>
          <div style={{ background:B.card,borderRadius:6,border:`1px solid ${B.border}`,padding:14 }}>
            <div style={{ ...O,fontSize:10,letterSpacing:3,color:B.accent,marginBottom:10 }}>HOW WE CHARGE</div>
            <div style={{ display:'flex',flexDirection:'column',gap:8 }}>
              {[
                {who:'Captain',    what:'Post a trip',     price:'FREE',  color:B.go},
                {who:'Crew member',what:'Request a seat',  price:'$2.99', color:B.accent},
              ].map(r=>(
                <div key={r.who} style={{ background:B.surf,borderRadius:4,padding:'10px 12px',border:`1px solid ${B.border}` }}>
                  <div style={{ display:'flex',justifyContent:'space-between',alignItems:'center' }}>
                    <div>
                      <div style={{ ...O,fontSize:10,letterSpacing:1,color:B.sun }}>{r.who}</div>
                      <div style={{ fontSize:10,color:B.dust,marginTop:2 }}>{r.what}</div>
                    </div>
                    <div style={{ ...O,fontSize:16,color:r.color }}>{r.price}</div>
                  </div>
                </div>
              ))}
            </div>
            <div style={{ fontSize:10,color:B.dust,lineHeight:1.6,marginTop:10 }}>
              The $2.99 covers secure matching, identity verification, and float plan generation.
            </div>
          </div>

          <div style={{ background:B.card,borderRadius:6,border:`1px solid ${B.border}`,padding:14 }}>
            <div style={{ ...O,fontSize:10,letterSpacing:3,color:B.danger,marginBottom:10 }}>🛡️ SAFETY</div>
            <div style={{ fontSize:11,color:B.sub,lineHeight:1.7,marginBottom:8 }}>Float plan auto-generated for every confirmed trip. Share it with someone on shore.</div>
            <div style={{ fontSize:11,color:B.dust }}>Coast Guard: <strong style={{ color:B.sun }}>VHF Ch 16</strong><br/>Emergency: <strong style={{ color:B.sun }}>1-800-424-8802</strong></div>
          </div>

          <div style={{ background:B.card,borderRadius:6,border:`1px solid ${B.border}`,padding:14 }}>
            <div style={{ ...O,fontSize:10,letterSpacing:3,color:B.accent,marginBottom:10 }}>THE RULES</div>
            {['Verified members only','Captain controls the boat','Cost = fuel & access only','Rate honestly every trip','No alcohol before departure'].map((r,i)=>(
              <div key={i} style={{ fontSize:11,color:B.sub,padding:'5px 0',borderBottom:i<4?`1px solid ${B.border}`:'none',display:'flex',gap:8 }}>
                <span style={{ ...O,fontSize:9,color:B.accent,flexShrink:0 }}>{String(i+1).padStart(2,'0')}</span>
                <span>{r}</span>
              </div>
            ))}
          </div>

          <button onClick={()=>setShowPost(true)} style={{ background:'transparent',color:B.accent,border:`2px solid ${B.accent}`,borderRadius:4,padding:'11px',...O,fontSize:11,letterSpacing:2,cursor:'pointer',width:'100%' }}>
            + POST YOUR TRIP — FREE
          </button>
        </div>
      </div>

      {requestTrip && <RequestModal  trip={requestTrip} onClose={()=>setRequestTrip(null)} />}
      {floatTrip   && <FloatPlan     trip={floatTrip}   onClose={()=>setFloatTrip(null)} />}
      {reviewTrip  && <CaptainReviewModal trip={reviewTrip} onClose={()=>setReviewTrip(null)} />}
      {showPost    && <PostTripModal onClose={()=>setShowPost(false)} />}
    </div>
  )
}
